export const USERS_PAGE_ROUTE = '/users'
export const NEWS_PAGE_ROUTE = '/news'
export const TOP_USERS_PAGE_ROUTE = '/top-users'
export const LOGOUT_PAGE_ROUTE = '/logout'
export const HOME_PAGE_ROUTE = '/'